### ISSUE TITLE
[Style]: revamp `benefits` section

### ISSUE THREAD

**Issue by Hemashree21** [harmeetsingh11/RefactorMate#37]
I want to work on adding the About Page so that the user who visits the website will get a brief idea about the different features. I will also make sure that the design is responsive. Here is one of the templates for reference.

![Screenshot 2024-05-20 163822](https://github.com/harmeetsingh11/RefactorMate/assets/138188163/c5041ad4-c399-4b8c-8299-16a7763c4b08)

@harmeetsingh11 can you please assign this to me?

**Comment by harmeetsingh11** [comment]
@Hemashree21 Thanks for opening the issue.

The benefits section currently duplicates the functionality of the about us section in our single-page landing app. Introducing a  "About Us" page would be redundant. Instead, you can revamp the "Benefits" section as per your shared screenshot to enhance its content and presentation. This issue is assigned to you. If you need any assistance, feel free to ask.
